# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Cache
version:      0.04
version_from: lib/Sledge/Cache.pm
installdirs:  site
requires:
    Class::Accessor:               0.22
    Test::Exception:               0.21
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
